name: Fastapi CI

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.12.2
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.2'

    - name: Upgrade pip and install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install --upgrade --no-cache-dir -r requirements.txt
    - name: Run tests
      run: |
        pytest
  deploy:
     needs: test
     runs-on: ubuntu-latest

     steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Azure 
        run: |
          ssh azureuser@20.121.64.202 << 'EOF'
            cd /fastapi-book-project
            git pull origin main
            source venv/bin/activate
            pip install --upgrade --no-cache-dir -r requirements.txt
            sudo systemctl restart nginx
            uvicorn main:app --host 0.0.0.0 --port 8000
          EOF
  
