name: FastAPI CI/CD

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.12.2
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.2'

      - name: Upgrade pip and install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install --upgrade --no-cache-dir -r requirements.txt

      - name: Run tests
        run: pytest

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Azure
        run: |
          ssh -o StrictHostKeyChecking=no azureuser@20.121.64.202 << 'EOF'
            cd /home/azureuser/fastapi-book-project || exit 1
            
            git pull origin main
            
            if [ -d "venv" ]; then
              source venv/bin/activate
            else
              echo "Virtual environment not found! Creating..."
              python3 -m venv venv
              source venv/bin/activate
            fi

            pip install --upgrade --no-cache-dir -r requirements.txt
            
            sudo systemctl restart fastapi-app && sudo systemctl status fastapi-app --no-pager
            
            sudo systemctl restart nginx && sudo systemctl status nginx --no-pager
          EOF

      - name: Health Check
        run: |
          for i in {1..5}; do
            curl -f http://20.121.64.202:8000/docs && exit 0 || sleep 5
          done
          echo "Health check failed!"
          exit 1
