name: Fastapi CI

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.12.2
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.2'

    - name: Upgrade pip and install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install --upgrade --no-cache-dir -r requirements.txt
